import { ReadableName } from "@/app/readable-name";
import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import { PortalHeader } from "@/app/portal-header";
import { PortalFooter } from "@/app/portal-footer";
import { BottomTabs } from "@/app/bottom-tabs";
export const dynamic="force-dynamic";
import {staticPageMetadata} from "@/lib/seo";
export const metadata=staticPageMetadata({title:"国内外の大型ポーカー大会 日程・スケジュール",description:"国内・海外の大型ポーカー大会の開催情報とスケジュール。開催地や日程で次の大会を探せます。",path:"/major-tournaments"});
export default async function Page({searchParams}:{searchParams:{scope?:string;q?:string;month?:string;page?:string}}){
 const db=await createClient();
 const [{data:{user}},{data,error}]=await Promise.all([db.auth.getUser(),db.from("major_tournaments").select("id,title,scope,location,venue,start_date,end_date,description").eq("active",true).order("start_date",{ascending:true,nullsFirst:false}).order("id",{ascending:true})]);
 const entries=(data||[]).map(e=>({...e,date:e.start_date?e.start_date.replaceAll("-",".")+(e.end_date&&e.end_date!==e.start_date?" — "+e.end_date.replaceAll("-","."):""):"開催日未定",month:e.start_date?.slice(0,7)||"",text:e.description||""}));
 const months=Array.from(new Set(entries.map(e=>e.month).filter(Boolean))).sort();
 const scope=["国内","海外"].includes(searchParams.scope||"")?searchParams.scope||"":"",q=searchParams.q?.trim()||"",month=searchParams.month||"";
 const results=entries.filter(e=>(!scope||e.scope===scope)&&(!month||e.month===month)&&(!q||(e.title+" "+e.location+" "+e.venue).toLowerCase().includes(q.toLowerCase())));
 const pageSize=6,totalPages=Math.max(1,Math.ceil(results.length/pageSize));
 const requestedPage=Number(searchParams.page||"1");
 const page=Number.isSafeInteger(requestedPage)&&requestedPage>0?Math.min(requestedPage,totalPages):1;
 const pageEntries=results.slice((page-1)*pageSize,page*pageSize);
 const pageHref=(target:number)=>{const p=new URLSearchParams();if(scope)p.set("scope",scope);if(q)p.set("q",q);if(month)p.set("month",month);if(target>1)p.set("page",String(target));return "/major-tournaments"+(p.size?"?"+p:"")+"#tournament-list";};
 const href=(value:string)=>{const p=new URLSearchParams();if(value)p.set("scope",value);if(q)p.set("q",q);if(month)p.set("month",month);return "/major-tournaments"+(p.size?"?"+p:"");};
 return <div><PortalHeader userEmail={user?.email}/><main className="ml-page"><Link className="ml-back" href="/">← TOPに戻る</Link>
 <header className="ml-hero"><div className="ml-hero-photo" role="img" aria-label="男女のプレイヤーが参加するポーカー大会"/><div className="ml-hero-copy"><span className="ml-eyebrow">MAJOR POKER TOURNAMENTS</span><h1>国内外大型大会を探す</h1><p>次のポーカー旅を、ここから。</p></div></header>
 <div className="ml-toolbar"><nav aria-label="大会の開催区分">{["","国内","海外"].map(v=><Link key={v} href={href(v)} className={scope===v?"ml-tab ml-active":"ml-tab"} aria-current={scope===v?"page":undefined}>{v||"すべて"}<small>{v?entries.filter(e=>e.scope===v).length:entries.length}</small></Link>)}</nav>
 <form method="get" action="/major-tournaments"><input type="hidden" name="scope" value={scope}/><label className="ml-sr" htmlFor="ml-q">大会名・国・都市を検索</label><input id="ml-q" name="q" defaultValue={q} placeholder="大会名・国・都市で検索"/><label className="ml-sr" htmlFor="ml-month">開催月</label><select id="ml-month" name="month" defaultValue={month}><option value="">開催月：すべて</option>{months.map(m=><option key={m} value={m}>{m.slice(0,4)}年{Number(m.slice(5))}月</option>)}</select><button type="submit">検索</button></form></div>
 <div className="ml-list-heading" id="tournament-list"><div><span className="ml-eyebrow">UPCOMING TOURNAMENTS</span><h2>{scope?scope+"の大会":"開催予定の大会"}<small>{results.length}件</small></h2></div><span>開催日順</span></div>
 <div className="ml-grid">{pageEntries.map(e=><article className="ml-card" key={e.id}><div className={"ml-cover "+(e.scope==="海外"?"ml-overseas":"")}><span className="ml-scope">{e.scope==="海外"?"海外大会":"国内大会"}</span><div><h3><ReadableName name={e.title} /></h3><small>POKER SUMMIT</small><span>{e.location}</span></div></div><div className="ml-body"><div className="ml-date"><span aria-hidden="true">▦</span>{e.date}</div><p className="ml-venue">⌖ {e.location} / {e.venue}</p><p className="ml-description">{e.text}</p><Link className="ml-detail" href={`/major-tournaments/${e.id}`}>詳細・スケジュールを見る <span>→</span></Link></div></article>)}</div>
 {results.length>0&&<p className="ml-range">{results.length}件中 {(page-1)*pageSize+1}〜{Math.min(page*pageSize,results.length)}件を表示</p>}
 {totalPages>1&&<nav className="ml-pagination" aria-label="大会一覧のページ切り替え">
 {page>1?<Link href={pageHref(page-1)}>← 前へ</Link>:<span aria-disabled="true">← 前へ</span>}
 <span className="ml-page-number">{page} / {totalPages}ページ</span>
 {page<totalPages?<Link href={pageHref(page+1)}>次へ →</Link>:<span aria-disabled="true">次へ →</span>}
 </nav>}
 {error?<div className="ml-empty"><p className="err">大会情報を読み込めませんでした。時間をおいて再度お試しください。</p></div>:!results.length&&<div className="ml-empty"><h3>{entries.length?"条件に合う大会がありません。":"大会情報は準備中です。"}</h3>{entries.length>0&&<><p>開催区分や検索キーワードを変更してください。</p><Link href="/major-tournaments">条件をクリア →</Link></>}</div>}
 <section className="ml-guide"><div><span className="ml-eyebrow">YOUR NEXT POKER TRIP</span><h2>行きたい大会が見つかったら。</h2><p>詳細ページでスケジュール・参加費・会場を確認。<br/>海外大会の時刻は、開催地の現地時間で掲載します。</p></div></section>
 </main><PortalFooter/><BottomTabs/><style>{`
.ml-range{text-align:center;font-size:12px;color:#795f39;margin:20px 0 12px}.ml-pagination{display:flex;justify-content:center;align-items:center;gap:14px;flex-wrap:wrap;margin:18px 0 26px}.ml-pagination>a,.ml-pagination>span[aria-disabled]{border:1px solid #dec99e;border-radius:7px;padding:11px 18px;font-size:13px;background:#faf5e8;color:#70521f}.ml-pagination>a:hover{background:#f1e3c1}.ml-pagination>span[aria-disabled]{opacity:.4}.ml-page-number{font-size:13px;color:#70521f}#tournament-list{scroll-margin-top:24px}
.ml-page{width:calc(100% - 40px);max-width:1140px;margin:0 auto;padding:24px 0 48px;color:#382b1e}.ml-back{font-size:13px;color:#795623;display:inline-block;margin-bottom:18px}.ml-notice{background:#fff9e9;border:1px solid #dfcb9c;border-radius:9px;padding:12px 16px;font-size:11px;color:#795b2d;display:flex;flex-wrap:wrap;gap:8px 18px;margin-bottom:18px}
.ml-hero{position:relative;min-height:240px;border-radius:14px;overflow:hidden;background:#dcc18f;display:flex;align-items:center}.ml-hero>img{position:absolute;right:0;top:0;width:55%;height:100%;object-fit:cover}.ml-hero:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,#d7b77a 0%,#e5cda3 43%,rgba(229,205,163,0) 64%)}.ml-hero>div{position:relative;z-index:1;padding:32px;max-width:65%}.ml-eyebrow{font-size:9px;letter-spacing:.18em;color:#936f2b;display:block}.ml-hero h1{font-size:32px;font-family:serif;font-weight:700;margin:12px 0;color:#fff;border:0;padding:0}.ml-hero p{font-size:17px;font-weight:700;margin:0 0 10px;color:#513713}.ml-hero small{font-size:11px;color:#765632;line-height:1.7}
.ml-toolbar{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;margin:24px 0 30px}.ml-toolbar nav{display:flex;gap:8px}.ml-tab{border-radius:7px;background:#f7f3e9;padding:10px 16px;font-size:12px;font-weight:700;display:flex;align-items:center;gap:10px;color:#694f27}.ml-tab small{font-size:10px;opacity:.7}.ml-active{background:#cfa938;color:#fff}.ml-toolbar form{display:flex;gap:7px;flex-wrap:wrap;align-items:center}.ml-toolbar input,.ml-toolbar select{width:auto!important;margin:0;background:#faf7ef;border:1px solid #ddceb5;border-radius:7px;padding:10px 12px;font-size:12px;color:#5d482c;height:40px;box-sizing:border-box}.ml-toolbar input{max-width:220px}.ml-toolbar button{height:40px;background:#cda535;border:0;border-radius:7px;padding:0 18px;font-size:12px;font-weight:700;color:#3b2a0f}
.ml-list-heading{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:18px;border-bottom:1px solid #dfd3bb;padding-bottom:12px}.ml-list-heading h2{margin:6px 0 0;font-size:22px;color:#372a1a}.ml-list-heading h2 small{font-size:12px;font-weight:400;color:#9b896d;margin-left:14px}.ml-list-heading>span{font-size:11px;color:#8f7956}
.ml-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}.ml-card{border:1px solid #e8dfce;border-radius:12px;overflow:hidden;background:#fff}.ml-cover{position:relative;height:195px;background:#383227 url('/images/major-tournament-banner.webp') 99% 50% / 202% auto no-repeat;overflow:hidden}.ml-cover>img{width:100%;height:100%;object-fit:cover;position:absolute;inset:0}.ml-cover:after{content:"";position:absolute;inset:0;background:linear-gradient(0deg,rgba(33,28,20,.94),rgba(33,28,20,.25))}.ml-overseas:after{background:linear-gradient(0deg,rgba(47,36,20,.92),rgba(47,36,20,.1))}.ml-scope{position:absolute;top:14px;left:14px;z-index:1;background:#fff7e4;color:#765820;border-radius:20px;padding:5px 11px;font-size:10px;font-weight:700}.ml-overseas .ml-scope{background:#e9eef0;color:#3a5b69}.ml-cover>div{position:absolute;bottom:20px;left:20px;right:20px;z-index:1;color:#fff}.ml-cover small{font-size:8px;letter-spacing:.14em;color:#e2c992}.ml-cover h3{font-family:Georgia,serif;font-size:22px;line-height:1.2;margin:8px 0;color:#fff}.ml-cover>div>span{font-size:10px;color:#e8dbbd}
.ml-body{padding:18px 20px}.ml-date{font-size:13px;font-weight:700;color:#684b23;display:flex;gap:8px;align-items:center}.ml-date>span{color:#b89037;font-size:17px}.ml-venue{font-size:10px;color:#8a7a60;line-height:1.6;margin:8px 0 12px}.ml-description{font-size:12px;color:#655744;line-height:1.8;min-height:44px}.ml-fee{display:flex;align-items:center;justify-content:space-between;padding:12px 0;margin-top:12px;border-top:1px solid #eee7da;font-size:11px}.ml-fee>span{color:#8b7a5f}.ml-fee strong{font-size:14px;color:#644822}.ml-detail{display:flex;align-items:center;justify-content:space-between;background:#fbf5e6;border:1px solid #e3d0a4;border-radius:7px;padding:11px 12px;color:#8a6725;font-weight:700;font-size:11px;margin-top:4px}.ml-detail:hover{background:#f4e7c9}.ml-placeholder{display:block;text-align:center;background:#f8f7f3;border-radius:7px;padding:12px;font-size:11px;color:#a1937a;margin-top:4px}
.ml-guide{margin-top:32px;background:#faf6ec;border:1px solid #e4d5b7;border-radius:12px;display:flex;align-items:center;justify-content:space-between;gap:20px;padding:26px 30px}.ml-guide h2{font-size:20px;margin:8px 0}.ml-guide p{font-size:12px;line-height:1.9;color:#8c7754;margin:0}.ml-guide>a{font-size:12px;font-weight:700;color:#846326;border:1px solid #dcc69a;border-radius:7px;padding:13px 18px;background:#fff;white-space:nowrap}.ml-empty{padding:50px 20px;text-align:center;border:1px solid #e6d9c0;border-radius:10px;color:#8a7656}.ml-empty h3{font-size:17px}.ml-empty p,.ml-empty a{font-size:13px}.ml-sr{position:absolute;width:1px;height:1px;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap}
@media(max-width:900px){.ml-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.ml-hero>div{max-width:80%}.ml-guide{align-items:flex-start;flex-direction:column}}
@media(max-width:600px){.ml-page{width:calc(100% - 24px);padding-top:18px}.ml-grid{grid-template-columns:1fr;gap:18px}.ml-hero{min-height:230px}.ml-hero>div{max-width:100%;padding:24px}.ml-hero>img{width:100%}.ml-hero:after{background:linear-gradient(90deg,rgba(209,173,110,.98),rgba(225,197,146,.85))}.ml-hero h1{font-size:28px}.ml-hero p{font-size:16px}.ml-toolbar{gap:14px}.ml-toolbar form{width:100%;display:grid;grid-template-columns:minmax(0,1fr) auto}.ml-toolbar input{max-width:none;grid-column:1/-1;width:100%!important}.ml-toolbar select{width:100%!important}.ml-toolbar input,.ml-toolbar select{font-size:16px}.ml-tab{padding:10px 18px}.ml-list-heading h2{font-size:21px}.ml-cover{height:210px}.ml-description{min-height:0}.ml-guide{padding:24px 20px}.ml-guide>a{white-space:normal}.ml-notice{font-size:10px}}

.ml-hero{min-height:190px;background:linear-gradient(110deg,#cfad70,#e6cea2)}
.ml-hero:after{display:none}
.ml-hero>.ml-hero-photo{position:absolute;right:0;top:0;width:50%;height:100%;max-width:none;padding:0;z-index:0;background-image:url('/images/major-tournament-banner.webp');background-size:202% auto;background-position:99% 50%;background-repeat:no-repeat}
.ml-hero>.ml-hero-copy{width:50%;max-width:none;box-sizing:border-box;padding:28px 30px}
.ml-hero h1{font-size:28px;line-height:1.4;margin:12px 0}
.ml-hero p{font-size:14px;font-weight:400;margin:0}
@media(max-width:600px){.ml-hero{min-height:180px}.ml-hero>.ml-hero-copy{padding:22px 16px}.ml-hero h1{font-size:23px}.ml-hero .ml-eyebrow{font-size:7px;line-height:1.6}.ml-hero p{font-size:12px;line-height:1.7}.ml-hero>.ml-hero-photo{background-size:auto 155%;background-position:99% 50%}}

.ml-cover{height:195px;margin:9px;border:1px solid #b58a31;border-radius:9px;background:linear-gradient(155deg,#ead8ae 0%,#fff8e6 58%,#dec38a 100%);display:flex;align-items:center;justify-content:center;text-align:center}
.ml-cover:after{inset:auto -10% -35% -10%;height:65%;background:rgba(255,255,255,.25);transform:rotate(-12deg);pointer-events:none}
.ml-cover.ml-overseas:after{background:rgba(255,255,255,.25)}
.ml-cover>div{position:relative;bottom:auto;left:auto;right:auto;width:100%;padding:36px 18px 22px;box-sizing:border-box;color:#563814}
.ml-cover h3{color:#563814;font-size:24px;line-height:1.35;overflow-wrap:anywhere;margin:12px 0}
.ml-cover small{display:block;font-size:8px;letter-spacing:.24em;color:#a27b35;margin:8px 0}
.ml-cover>div>span{color:#8a6b3b}
.ml-scope{top:10px;left:10px}
`}</style></div>;
}
