"use client";
import {useEffect,useRef,useState,type ReactNode} from "react";
import {useFormState,useFormStatus} from "react-dom";
import {useRouter} from "next/navigation";
import Link from "next/link";
import {chatAction,offerAction,markNotificationsRead} from "./actions";
import styles from "./chat.module.css";
export type Terms={revision:number;contract_type:string;payment_method:string;payment_date:string;notes:string};
function Submit({children}:{children:ReactNode}){const {pending}=useFormStatus();return <button className={styles.primary} disabled={pending} type="submit">{pending?"保存中…":children}</button>;}
export function LiveChat(){const router=useRouter();useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==="visible")router.refresh();},15000);return ()=>clearInterval(timer);},[router]);return null;}
export function ChatForm({actor,record,operation,children,button,reset=false}:{actor:"store"|"dealer";record:string;operation:string;children:ReactNode;button:string;reset?:boolean}){
 const [state,action]=useFormState(chatAction,{error:"",success:0});const router=useRouter(),form=useRef<HTMLFormElement>(null);const [nonce,setNonce]=useState("");
 useEffect(()=>setNonce(crypto.randomUUID()),[]);
 useEffect(()=>{if(state.success){if(reset)form.current?.reset();setNonce(crypto.randomUUID());router.refresh();}},[state.success,reset,router]);
 return <form ref={form} action={action} className={styles.form}><input type="hidden" name="actor" value={actor}/><input type="hidden" name="record" value={record}/><input type="hidden" name="operation" value={operation}/><input type="hidden" name="nonce" value={nonce}/>{children}{state.error&&<p role="alert" className={styles.error}>{state.error}</p>}{state.success>0&&!state.error&&operation!=="send"&&<p role="status">保存しました。</p>}<Submit>{button}</Submit></form>;
}
export function MessageHistory({children,lastId,latest}:{children:ReactNode;lastId:string;latest:boolean}){const box=useRef<HTMLDivElement>(null),atBottom=useRef(true);useEffect(()=>{if(latest&&atBottom.current&&box.current)box.current.scrollTop=box.current.scrollHeight;},[lastId,latest]);return <div ref={box} className={styles.messages} aria-label="メッセージ履歴" onScroll={()=>{const el=box.current;if(el)atBottom.current=el.scrollHeight-el.clientHeight-el.scrollTop<60;}}>{children}</div>;}
export function ConsentForm({actor,record}:{actor:"store"|"dealer";record:string}){return <ChatForm actor={actor} record={record} operation="consent" button="同意してチャットを始める"><p>勤務条件・報酬・支払方法は当事者で確認してください。双方の合意前の連絡先交換・外部誘導、ハラスメント、不要な個人情報の送信は禁止します。合意後に開示された連絡先は、その勤務の連絡にのみ使用してください。</p><p>通報されたチャットは、運営が対応のために内容を確認します。ブロックしても確定済みの勤務はキャンセルされません。</p><p><Link href="/terms" target="_blank">利用規約</Link> ／ <Link href="/privacy" target="_blank">プライバシーポリシー</Link></p><label className={styles.check}><input name="agreed" type="checkbox" required/>規約とチャットの注意事項に同意します。</label></ChatForm>;}
export function TermsForm({actor,record,terms}:{actor:"store"|"dealer";record:string;terms:Terms|null}){return <ChatForm actor={actor} record={record} operation="terms" button="条件を保存する"><input name="revision" type="hidden" value={terms?.revision||0}/><label>契約形態<select name="contract_type" required defaultValue={terms?.contract_type||""}><option value="">選択してください</option><option value="employment">雇用（アルバイト等）</option><option value="contract">業務委託</option></select></label><label>支払方法<select name="payment_method" required defaultValue={terms?.payment_method||""}><option value="">選択してください</option><option value="bank">銀行振込</option><option value="cash">現金</option></select></label><label>支払日<input name="payment_date" maxLength={100} required defaultValue={terms?.payment_date||""} placeholder="例：翌月15日"/></label><label>その他の合意事項<textarea name="notes" rows={4} maxLength={2000} defaultValue={terms?.notes||""} placeholder="交通費・深夜手当・税の取扱い・キャンセル時の対応など"/></label><p className={styles.muted}>変更すると双方の合意を解除します。契約形態は実際の働き方に合わせて選択してください。</p></ChatForm>;}
export function OfferForm({dealer,options}:{dealer:string;options:{value:string;label:string}[]}){const [state,action]=useFormState(offerAction,{error:"",success:0});return <form action={action} className={styles.form}><input name="dealer" type="hidden" value={dealer}/><label>オファーする勤務日<select name="shift" required defaultValue=""><option value="">選択してください</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>{state.error&&<p role="alert" className={styles.error}>{state.error}</p>}<Submit>オファーしてチャットを開く</Submit></form>;}

export function MarkNotificationsRead({actor,record,events}:{actor:"store"|"dealer";record:string;events:string[]}){const signature=events.join(",");useEffect(()=>{let active=true;const mark=()=>{if(document.visibilityState==="visible")void markNotificationsRead(actor,record,signature.split(",").filter(Boolean)).then(()=>{if(active)window.dispatchEvent(new Event("matching-notifications-changed"));});};mark();document.addEventListener("visibilitychange",mark);return()=>{active=false;document.removeEventListener("visibilitychange",mark);};},[actor,record,signature]);return null;}
